# Generated by Django 2.0.13 on 2020-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('hindi', models.IntegerField()),
                ('english', models.IntegerField()),
                ('science', models.IntegerField()),
                ('homescience', models.IntegerField()),
                ('socialscience', models.IntegerField()),
                ('drawing', models.IntegerField()),
            ],
        ),
    ]
